export const FETCH_APARTMENTS_LIST = 'FETCH_APARTMENTS_LIST';
export const FETCH_APARTMENTS_LIST_BY_LOCATION = 'FETCH_APARTMENTS_LIST_BY_LOCATION';
export const FILTER_APARTMENTS_LIST = 'FILTER_APARTMENTS_LIST';
export const CLEAN_FILTER = 'CLEAN_FILTER';
export const FETCH_APARTMENT = 'FETCH_APARTMENT';
export const FETCH_LOCATIONS_LIST = 'FETCH_LOCATIONS_LIST';
